nelmio_api_doc:
    documentation:
        info:
            title: "Movies API"
            description: "Movies database API"
            version: 1.0.0
    routes:
        path_patterns:
            - ^/api(?!/doc$)
    models:
        use_jms: true