#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
    prefix: /api
    resource: '../src/Controller'

movies:
    type: rest
    resource: App\Controller\MoviesController

persons:
    type: rest
    resource: App\Controller\PersonsController

user:
    resource: App\Controller\UsersController
    type: rest

tokens:
    resource: App\Controller\TokensController
    type: rest

images:
    resource: App\Controller\ImagesController
    type: rest

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }